#pragma once
// {{NAME}} -- {{CATEGORY}} app. Generated by tools/port/new_app.py.
// Conforms to docs/merge/RULESET.md. Fill in the TODOs, then run the checklist.
// Register it in src/activities/apps/AppRegistry.cpp so the launcher can find it.
#include <cstdint>

#include "activities/Activity.h"

class {{CLASS}}Activity final : public Activity {
 public:
  explicit {{CLASS}}Activity(GfxRenderer& renderer, MappedInputManager& mappedInput)
      : Activity("{{NAME}}", renderer, mappedInput) {}

  void onEnter() override;
  void onExit() override;
  void loop() override;
  void render(RenderLock&&) override;

 private:
  // RULESET: fixed buffers, no std::string in hot paths, cap every collection.
  // Keep sizeof(*this) small; put heavy buffers on the heap in onEnter().
  bool dirty = true;  // set when state changes; drives requestUpdate()
};
